/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_0_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_1_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_2_MODE_INACTIVE 0x00u

/*! @name PIO1_0 (number 11), LED_VERDE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_VERDE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_VERDE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_VERDE_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_VERDE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_VERDE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_1 (number 14), LED_AZUL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_AZUL_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_AZUL_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_AZUL_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_AZUL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_AZUL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_2 (number 16), LED_ROJO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_ROJO_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_ROJO_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_ROJO_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_ROJO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_ROJO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_24 (number 20), RXD
  @{ */
#define BOARD_INITPINS_RXD_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_RXD_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RXD_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_25 (number 19), TXD
  @{ */
#define BOARD_INITPINS_TXD_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_TXD_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TXD_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
